Readme Update to use AvatarCreator wording
readyplayerme/UE5-WebView-Example pull request #2
Opened 2022-07-07 10:16 UTC by HarrisonHough

Small wording and title updates

2022-07-07 11:23 UTC, GevorgRPM approved these changes

2022-07-07 13:42 UTC, bfercher requested changes
Can you please use Avatar Creator instead of AvatarCreator. And slightly change heading 🙏

2022-07-07 13:42 UTC, bfercher commented on README.md
> +# Example UE AvatarCreator Integration
UE Avatar Creator Integration Example

2022-07-07 13:42 UTC, bfercher commented on README.md
> +This repository contains an Unreal Engine 5 sample project that uses the Unreal Engine Web Browser module (and Web Browser Widget) to embed the Ready Player Me AvatarCreator inside an application to
please use a blank between Avatar and Creator

2022-07-07 13:42 UTC, bfercher commented on README.md
> +The WebBrowserDemo map located in the `Content` folder is a good starting point for anybody wanting to use the Web Browser module to seamlessly integrate our RPM AvatarCreator into you game or applic
Please use a blank between Avatar and Creator

2022-07-08 07:09 UTC, HarrisonHough commented on README.md
> +The WebBrowserDemo map located in the `Content` folder is a good starting point for anybody wanting to use the Web Browser module to seamlessly integrate our RPM AvatarCreator into you game or applic
done

2022-07-08 07:09 UTC, HarrisonHough commented on README.md
> +# Example UE AvatarCreator Integration
done

2022-07-08 07:10 UTC, bfercher approved these changes
🥇

2022-07-08 07:11 UTC, merged